version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - 5432:5432
  keycloak:
    image: keycloak/keycloak
    command: start-dev
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_SCHEMA: public
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/real-export.json
    volumes:
      - type: bind
        source: ./realm-export.json
        target: /tmp/real-export.json
        read_only: true
    ports:
      - target: 8080
        published: ${KEYCLOAK_PUBLISHED_PORT}
        protocol: tcp
        mode: host
    #depends_on:
    #  - postgres
